<div id="contact_col1">
    <?php echo $this->form; ?>
</div>
<div id="contact_col2">
    <div id="contact-info">
        
           	<h2>Adres Firmy</h2>
                66-300  Międzyrzecz <br />
                ul. Reymonta 7<br />
                Tel: 090-010-0860<br/>
                Fax: 090-010-0860
    </div>
<iframe width="460" height="230" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.pl/maps?q=reymonta+7+mi%C4%99dzyrzecz&amp;ie=UTF8&amp;hl=en&amp;hq=&amp;hnear=Reymonta+7,+66-300+Mi%C4%99dzyrzecz,+mi%C4%99dzyrzecki,+lubuskie&amp;ll=52.451231,15.582309&amp;spn=0.000953,0.002476&amp;t=h&amp;z=14&amp;layer=c&amp;cbll=52.451124,15.582576&amp;panoid=4vrNgtfnfL53eGF_DZxyoQ&amp;cbp=12,325.02,,0,-5.07&amp;source=embed&amp;output=svembed"></iframe>
</div>