<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
    <head>
        <?php echo $this->headTitle($this->tytul) ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->headMeta() ?>
    </head>
    <body>
        <div id="header">
            <div id="header-wrapper">
                <div id="languages-wrapper">
                    <li><a href="<?php echo $this->url(array(
                        'lang' => 'en',
                        'module' => 'default',
                        'controller' => 'index',
                        'action' => 'domowa'),null, true);
                     ?>">English</a></li>
                    <li><a href="<?php echo $this->url(array(
                        'lang' => 'de',
                        'module' => 'default',
                        'controller' => 'index',
                        'action' => 'domowa'),null, true);
                     ?>">Deutsch</a></li>
                     <li><a href="<?php echo $this->url(array(
                        'lang' => 'nl',
                        'module' => 'default',
                        'controller' => 'index',
                        'action' => 'domowa'),null, true);
                     ?>">Dutch</a></li>
                    <li><a href="<?php echo $this->url(array(
                        'lang' => 'pl',
                        'module' => 'default',
                        'controller' => 'index',
                        'action' => 'domowa'),null, true);
                     ?>">Polski</a></li>
                </div>
                <div id="logo-wrapper">
                        <div class="logo">
                            <h1><a href="<?php echo $this->url(array(
                            'lang' => Zend_Registry::get('lang'),
                            'module' => 'default',
                            'controller' => 'index',
                            'action' => 'domowa'),null, true); ?>) ?>">Tytul</a></h1>
                        </div>
                </div>
                <div id="nav-wrapper">
                    <div id="nav">
                        <ul>
                            <li><a href="<?php echo $this->url(array(
                            'lang' => Zend_Registry::get('lang'),
                            'module' => 'default',
                            'controller' => 'index',
                            'action' => 'domowa'),null, true); ?>" class="selected">Home</a></li>
                            
                            <li><a href="<?php echo $this->url(array(
                            'lang' => Zend_Registry::get('lang'),
                            'module' => 'default',
                            'controller' => 'index',
                            'action' => 'ofirmie'),null, true); ?>"><?php echo $this->translate('ofirmie');?></a></li>
                            <li><a href="<?php echo $this->url(array(
                            'lang' => Zend_Registry::get('lang'),
                            'module' => 'default',
                            'controller' => 'index',
                            'action' => 'galeria'),null, true); ?>"><?php echo $this->translate('galeria'); ?></a></li>
                            <li><a href="<?php echo $this->url(array(
                            'lang' => Zend_Registry::get('lang'),
                            'module' => 'default',
                            'controller' => 'index',
                            'action' => 'kontakt'),null, true); ?>">Kontakt</a></li>
                        </ul>
                    </div>
                </div>
                
            </div>
            <div class="slider-wrapper">
		<div id="slider" class="nivoSlider">
			<img src="<?php echo $this->baseUrl('/images/sliderPhotos/slider3.jpg'); ?>" alt="" />
			<img src="<?php echo $this->baseUrl('/images/sliderPhotos/slider1.jpg'); ?>" alt="" />
			<img src="<?php echo $this->baseUrl('/images/sliderPhotos/slider2.jpg'); ?>" alt="" />
			<img src="<?php echo $this->baseUrl('/images/sliderPhotos/slider0.jpg'); ?>" alt="" />
			<img src="<?php echo $this->baseUrl('/images/sliderPhotos/slider4.jpg'); ?>" alt="" />
		</div>
	</div>
        </div>
        
       
            

            
            <div id="content-wrapper">
               <div id="main-content">
                
                    <?php echo $this->layout()->content; ?>
                
                </div>  
            </div>
        <div id="templatemo_bottom_wrapper">
    <div id="templatemo_bottom">
    	<div class="col one_third">
        	<h4><span></span></h4>
            <div class="bottom_box">
            </div>
        </div>
        <div class="col one_third">
        	<h4><span></span></h4>            
        </div>
        <div class="col one_third no_margin_right">
        	<h4><span></span></h4>           
        </div>
        
    	<div class="cleaner"></div>
    </div> 
</div> 

<div id="templatemo_footer_wrapper">
    <div id="templatemo_footer">
    	Copyright © 2013  | Designed by Ramt1n
    </div> 
</div> 
       
        <script type="text/javascript">
	$(window).load(function() {
		$('#slider').nivoSlider();
	});
        </script>
         <script type="text/javascript" charset="utf-8">
                    $(document).ready(function(){
                    $("a[rel^='prettyPhoto']").prettyPhoto({theme:'light_square'});
                });
            </script>
        <script type="text/javascript"> Cufon.now(); </script>
    </body>
   
</html>
