<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
    <head>
        <?php echo $this->headTitle('logowanie') ?>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/style2.css') ?>" />
        <?php echo $this->headScript() ?>
        <?php echo $this->headMeta() ?>
    </head>
    <body>
        <?php echo $this->form; ?>
    </body>